package net.pearx.puramagio

import net.minecraftforge.fml.common.Mod
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent
import org.apache.logging.log4j.Logger

@Mod(modLanguageAdapter = "net.shadowfacts.forgelin.KotlinAdapter",
    name = NAME,
    modid = ID,
    version = VERSION,
    acceptedMinecraftVersions = ACCEPTED_MINECRAFT_VERSIONS,
    dependencies = DEPENDENCIES,
    acceptableRemoteVersions = "*")
object CraftDumper {
    lateinit var log: Logger private set

    @Mod.EventHandler
    fun preInit(event: FMLPreInitializationEvent) {
        log = event.modLog
        with(event.modMetadata) {
            autogenerated = false
            modId = ID
            name = NAME
            description = DESCRIPTION
            version = VERSION
            authorList = AUTHORS
        }
    }
}