package net.pearx.purmag;

import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.common.config.Configuration;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLServerStartingEvent;
import net.pearx.purmag.common.*;
import net.pearx.purmag.common.blocks.BlockRegistry;
import net.pearx.purmag.common.infofield.IfRegistry;
import net.pearx.purmag.common.items.ItemRegistry;
import net.pearx.purmag.common.networking.NetworkManager;
import net.pearx.purmag.common.sip.SipType;
import net.pearx.purmag.common.sip.SipTypeRegistry;
import net.pearx.purmag.common.tiles.TileRegistry;
import net.pearx.purmag.common.worldgen.WorldgenRegistry;
import net.pearx.purmag.server.commands.CommandIf;

import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

/**
 * Created by mrAppleXZ on 08.04.17 10:31.
 */
@Mod(name = PurMag.Name, modid = PurMag.ModId)
public class PurMag
{
    public static PurMag instance;

    public static final String ModId = "purmag";
    public static final String Name = "Purificati Magicae";
    public static final String Version = "1.0.0";

    public SipTypeRegistry sip = new SipTypeRegistry();
    public IfRegistry if_registry = new IfRegistry();
    public PMConfig config = new PMConfig();
    public Configuration configFile;

    @SidedProxy(clientSide = "net.pearx.purmag.client.ClientProxy", serverSide = "net.pearx.purmag.server.ServerProxy")
    public static CommonProxy proxy;

    @Mod.EventHandler
    public void preInit(FMLPreInitializationEvent e)
    {
        instance = this;
        setupMetadata(e.getModMetadata());

        configFile = new Configuration(new File(e.getModConfigurationDirectory(), "Purificati Magicae.cfg"));
        setupConfig();

        sip.setup();
        BlockRegistry.setup();
        ItemRegistry.setup();
        TileRegistry.setup();
        SoundRegistry.setup();
        if_registry.setup();
        CapabilityRegistry.setup();
        NetworkManager.setup();
        WorldgenRegistry.setup();

        proxy.preInit();
        MinecraftForge.EVENT_BUS.register(new CommonEvents());
    }

    @Mod.EventHandler
    public void init(FMLInitializationEvent e)
    {
        proxy.init();
    }

    private void setupMetadata(ModMetadata data)
    {
        data.autogenerated = false;
        ArrayList<String> a = new ArrayList<>();
        a.add("mrAppleXZ");
        data.credits = "DrVexsear - artist\nafdw & Prototik - cool guys";
        data.authorList = a;
        data.description = "Purificati Magicae";
        data.modId = PurMag.ModId;
        data.name = PurMag.Name;
        data.version = PurMag.Version;
    }

    private void setupConfig()
    {
        config.genSeaCrystals = configFile.getBoolean("Generate Sea Crystals", "WORLD", true, "");
        config.genRockCrystals = configFile.getBoolean("Generate Rock Crystals", "WORLD", true, "");
        config.genFlameCrystals = configFile.getBoolean("Generate Flame Crystals", "WORLD", true, "");

        config.chanceSeaCrystal = configFile.getFloat("Sea Crystal Chance", "WORLD", 0.3f, 0f, 1f, "Chance to generate a Sea Crystal. 1 - 100%, 0 - 0%.");
        config.chanceRockCrystal = configFile.getFloat("Rock Crystal Chance", "WORLD", 0.3f, 0f, 1f, "Chance to generate a Rock Crystal. 1 - 100%, 0 - 0%.");
        config.chanceFlameCrystal = configFile.getFloat("Flame Crystal Chance", "WORLD", 0.3f, 0f, 1f, "Chance to generate a Flame Crystal. 1 - 100%, 0 - 0%.");

        if(configFile.hasChanged())
            configFile.save();
    }

    @Mod.EventHandler
    public void serverStartup(FMLServerStartingEvent e)
    {
        e.registerServerCommand(new CommandIf());
    }
}
