package net.pearx.purmag;

import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.pearx.purmag.registries.*;

import java.util.ArrayList;

/**
 * Created by mrAppleXZ on 08.04.17 10:31.
 */
@Mod(name = PurmagCore.Name, modid = PurmagCore.ModId)
public class PurmagCore
{
    public static PurmagCore instance;

    public static SipTypeRegistry CrystalReg = new SipTypeRegistry();

    public static final String ModId = "purmag";
    public static final String Name = "Purificati Magicae";
    public static final String Version = "1.0.0";

    @SidedProxy(clientSide = "net.pearx.purmag.ClientProxy", serverSide = "net.pearx.purmag.ServerProxy")
    public static CommonProxy proxy;

    @Mod.EventHandler
    public void preInit(FMLPreInitializationEvent e)
    {
        instance = this;
        setupMetadata(e.getModMetadata());
        BlockRegistry.setup();
        ItemRegistry.setup();
        TileRegistry.setup();
        SoundRegistry.setup();
        proxy.preInit();
        MinecraftForge.EVENT_BUS.register(new PMEvents());

    }

    @Mod.EventHandler
    public void init(FMLInitializationEvent e)
    {
        proxy.init();
    }

    public void setupMetadata(ModMetadata data)
    {
        data.autogenerated = false;
        ArrayList<String> a = new ArrayList<>();
        a.add("mrAppleXZ");
        data.credits = "DrVexsear - many ideas\nafdw & Prototik - cool guys";
        data.authorList = a;
        data.description = "Purificati Magicae";
        data.modId = PurmagCore.ModId;
        data.name = PurmagCore.Name;
        data.version = PurmagCore.Version;
    }
}
